/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package acuario1;

import java.awt.Color;
import java.awt.Font;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;

/**
 *
 * @author pao_g
 */
public class Comprar extends javax.swing.JFrame {

    /**
     * Creates new form Comprar
     */
    
   static int tipo;
   int money;
   
   public Clip clip;
    
    public void sonido(String arch) throws LineUnavailableException, UnsupportedAudioFileException, IOException{
        clip=AudioSystem.getClip();
        clip.open(AudioSystem.getAudioInputStream(getClass().getResourceAsStream("/Sonido/"+arch)));
        clip.start();
    }
    
    public Comprar() {
        initComponents();
        this.setLocationRelativeTo(null); 
        this.setBackground(new Color(0,0,0,0));
   
        
        this.jButtonPez1.setFont(new Font("Wavepool",0,15));
        this.jButton1.setFont(new Font("Wavepool",0,15));
        this.jButton1.setOpaque(false);
        this.jButton1.setContentAreaFilled(false);
        this.jButtonPez2.setFont(new Font("Wavepool",0,15));
        this.jButtonPez3.setFont(new Font("Wavepool",0,15));
        this.jButtonPez4.setFont(new Font("Wavepool",0,15));
        this.jButtonPez5.setFont(new Font("Wavepool",0,15));
        
        money=Integer.parseInt(pecera.dinero);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonPez1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButtonPez2 = new javax.swing.JButton();
        jButtonPez3 = new javax.swing.JButton();
        jButtonPez4 = new javax.swing.JButton();
        jButtonPez5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(200, 300));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jButtonPez1.setBackground(new java.awt.Color(255, 255, 255));
        jButtonPez1.setForeground(new java.awt.Color(0, 102, 102));
        jButtonPez1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/peces/fish(1) - copia.gif"))); // NOI18N
        jButtonPez1.setText(" $100");
        jButtonPez1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPez1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPez1);
        jButtonPez1.setBounds(20, 10, 160, 50);

        jButton1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 0, 0));
        jButton1.setText("CERRAR");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(50, 260, 100, 30);

        jButtonPez2.setBackground(new java.awt.Color(255, 255, 255));
        jButtonPez2.setForeground(new java.awt.Color(0, 102, 102));
        jButtonPez2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/peces/fish(2) - copia.gif"))); // NOI18N
        jButtonPez2.setText("   $200");
        jButtonPez2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPez2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPez2);
        jButtonPez2.setBounds(20, 60, 160, 50);

        jButtonPez3.setBackground(new java.awt.Color(255, 255, 255));
        jButtonPez3.setForeground(new java.awt.Color(0, 102, 102));
        jButtonPez3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/peces/fish(4) - copia.gif"))); // NOI18N
        jButtonPez3.setText(" $300");
        jButtonPez3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPez3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPez3);
        jButtonPez3.setBounds(20, 110, 160, 50);

        jButtonPez4.setBackground(new java.awt.Color(255, 255, 255));
        jButtonPez4.setForeground(new java.awt.Color(0, 102, 102));
        jButtonPez4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/peces/fish(3) - copia.gif"))); // NOI18N
        jButtonPez4.setText(" $400");
        jButtonPez4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPez4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPez4);
        jButtonPez4.setBounds(20, 160, 160, 50);

        jButtonPez5.setBackground(new java.awt.Color(255, 255, 255));
        jButtonPez5.setForeground(new java.awt.Color(0, 102, 102));
        jButtonPez5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/peces/fish(5) - copia.gif"))); // NOI18N
        jButtonPez5.setText("  $500");
        jButtonPez5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPez5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPez5);
        jButtonPez5.setBounds(20, 210, 160, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoPe.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -10, 260, 320);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       try {
           // TODO add your handling code here:
           sonido("cerrar.wav");
       } catch (LineUnavailableException ex) {
           Logger.getLogger(Comprar.class.getName()).log(Level.SEVERE, null, ex);
       } catch (UnsupportedAudioFileException ex) {
           Logger.getLogger(Comprar.class.getName()).log(Level.SEVERE, null, ex);
       } catch (IOException ex) {
           Logger.getLogger(Comprar.class.getName()).log(Level.SEVERE, null, ex);
       }
        
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonPez5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPez5ActionPerformed
        // TODO add your handling code here:
         if(money>=500){
            
            try {
                sonido("splash.wav");
                tipo=5;
                money=money-500;
                pecera.dinero=Integer.toString(money);
            } catch (LineUnavailableException ex) {
                Logger.getLogger(Comprar.class.getName()).log(Level.SEVERE, null, ex);
            } catch (UnsupportedAudioFileException ex) {
                Logger.getLogger(Comprar.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Comprar.class.getName()).log(Level.SEVERE, null, ex);
            }
           
        }
        else{
            try {
                sonido("insuficiente.wav");
            } catch (LineUnavailableException ex) {
                Logger.getLogger(Comprar.class.getName()).log(Level.SEVERE, null, ex);
            } catch (UnsupportedAudioFileException ex) {
                Logger.getLogger(Comprar.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Comprar.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonPez5ActionPerformed

    private void jButtonPez1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPez1ActionPerformed
        // TODO add your handling code here:
        //tipo1
        
        if(money>=100){
            
            try {
                sonido("splash.wav");
                tipo=1;
                money=money-100;
                pecera.dinero=Integer.toString(money);
            } catch (LineUnavailableException ex) {
                Logger.getLogger(Comprar.class.getName()).log(Level.SEVERE, null, ex);
            } catch (UnsupportedAudioFileException ex) {
                Logger.getLogger(Comprar.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Comprar.class.getName()).log(Level.SEVERE, null, ex);
            }
           
        }
        else{
            try {
                sonido("insuficiente.wav");
            } catch (LineUnavailableException ex) {
                Logger.getLogger(Comprar.class.getName()).log(Level.SEVERE, null, ex);
            } catch (UnsupportedAudioFileException ex) {
                Logger.getLogger(Comprar.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Comprar.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
               
        
    }//GEN-LAST:event_jButtonPez1ActionPerformed

    private void jButtonPez2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPez2ActionPerformed
        // TODO add your handling code here:
        
         if(money>=200){
            
            try {
                sonido("splash.wav");
                tipo=2;
                money=money-200;
                pecera.dinero=Integer.toString(money);
            } catch (LineUnavailableException ex) {
                Logger.getLogger(Comprar.class.getName()).log(Level.SEVERE, null, ex);
            } catch (UnsupportedAudioFileException ex) {
                Logger.getLogger(Comprar.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Comprar.class.getName()).log(Level.SEVERE, null, ex);
            }
           
        }
        else{
            try {
                sonido("insuficiente.wav");
            } catch (LineUnavailableException ex) {
                Logger.getLogger(Comprar.class.getName()).log(Level.SEVERE, null, ex);
            } catch (UnsupportedAudioFileException ex) {
                Logger.getLogger(Comprar.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Comprar.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonPez2ActionPerformed

    private void jButtonPez3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPez3ActionPerformed
        // TODO add your handling code here:
        
         if(money>=300){
            
            try {
                sonido("splash.wav");
                tipo=3;
                money=money-300;
                pecera.dinero=Integer.toString(money);
            } catch (LineUnavailableException ex) {
                Logger.getLogger(Comprar.class.getName()).log(Level.SEVERE, null, ex);
            } catch (UnsupportedAudioFileException ex) {
                Logger.getLogger(Comprar.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Comprar.class.getName()).log(Level.SEVERE, null, ex);
            }
           
        }
        else{
            try {
                sonido("insuficiente.wav");
            } catch (LineUnavailableException ex) {
                Logger.getLogger(Comprar.class.getName()).log(Level.SEVERE, null, ex);
            } catch (UnsupportedAudioFileException ex) {
                Logger.getLogger(Comprar.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Comprar.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonPez3ActionPerformed

    private void jButtonPez4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPez4ActionPerformed
        // TODO add your handling code here:
         if(money>=400){
            
            try {
                sonido("splash.wav");
                tipo=4;
                money=money-400;
                pecera.dinero=Integer.toString(money);
            } catch (LineUnavailableException ex) {
                Logger.getLogger(Comprar.class.getName()).log(Level.SEVERE, null, ex);
            } catch (UnsupportedAudioFileException ex) {
                Logger.getLogger(Comprar.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Comprar.class.getName()).log(Level.SEVERE, null, ex);
            }
           
        }
        else{
            try {
                sonido("insuficiente.wav");
            } catch (LineUnavailableException ex) {
                Logger.getLogger(Comprar.class.getName()).log(Level.SEVERE, null, ex);
            } catch (UnsupportedAudioFileException ex) {
                Logger.getLogger(Comprar.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Comprar.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonPez4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Comprar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Comprar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Comprar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Comprar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonPez1;
    private javax.swing.JButton jButtonPez2;
    private javax.swing.JButton jButtonPez3;
    private javax.swing.JButton jButtonPez4;
    private javax.swing.JButton jButtonPez5;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
